clc;
t=input('input the time period=');
a=input('input the amplitude of  signal=');
n=input('input the total sampling number=');
f=1/t;
s=t/n;
c=0:s:t;
y=a*sin(2*pi*f*c);
subplot(1,2,2);
stem(c,y);
grid;
z=a*cos(2*pi*f*c);
subplot(1,2,1);
stem(c,z);
grid;
